### ISSUE TITLE
Program fails if special base is not included

### ISSUE THREAD

**Issue by SuwinTzi** [AoKishuba/aps-calc#2]
I tried various combinations and for whatever reason, if I type in "done" at the special base option, after completing the rest of the entries the program fails.  The error message was too fast for me to read it properly however.

**Comment by AoKishuba** [comment]
Edit: Yes, it seems the issue was that the method used to log the shell info to the console did not check whether a base was present before trying to log the name of the base module; this would throw an error if no base had been set.  I've updated the main branch.

I think I've fixed the issue.  Try overwriting the ShellCalc class with the following:

[ShellCalc.txt](https://github.com/AoKishuba/ApsCalc/files/6475408/ShellCalc.txt)
